services:

  discovery-service:
    container_name: edgecloud-discovery-service
    build:
      context: ../../../../edgecloud-discovery-service
    ports:
      - "${DISCOVERY_PORT}:8761"
    networks:
      - edgecloud-network

  api-gateway:
    container_name: edgecloud-api-gateway
    build:
      context: ../../../../edgecloud-api-gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    depends_on:
      - discovery-service
    environment:
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    networks:
      - edgecloud-network

  auth-mysql:
    image: mysql:8.0
    container_name: edgecloud-auth-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MYSQL_USER: ${AUTH_DB_USER}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:3306"
    volumes:
      - auth_mysql_data:/var/lib/mysql
    networks:
      - edgecloud-network

  monitoring-mysql:
    image: mysql:8.0
    container_name: edgecloud-monitoring-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MONITORING_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MONITORING_DB_ROOT_PASSWORD}
      MYSQL_USER: ${MONITORING_DB_USER}
      MYSQL_PASSWORD: ${MONITORING_DB_PASSWORD}
    ports:
      - "${MONITORING_DB_PORT}:3306"
    volumes:
      - monitoring_mysql_data:/var/lib/mysql
    networks:
      - edgecloud-network

  device-mysql:
    image: mysql:8.0
    container_name: edgecloud-device-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DEVICE_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DEVICE_DB_ROOT_PASSWORD}
      MYSQL_USER: ${DEVICE_DB_USER}
      MYSQL_PASSWORD: ${DEVICE_DB_PASSWORD}
    ports:
      - "${DEVICE_DB_PORT}:3306"
    volumes:
      - device_mysql_data:/var/lib/mysql
    networks:
      - edgecloud-network

  alert-mysql:
    image: mysql:8.0
    container_name: edgecloud-alert-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${ALERT_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${ALERT_DB_ROOT_PASSWORD}
      MYSQL_USER: ${ALERT_DB_USER}
      MYSQL_PASSWORD: ${ALERT_DB_PASSWORD}
    ports:
      - "${ALERT_DB_PORT}:3306"
    volumes:
      - alert_mysql_data:/var/lib/mysql
    networks:
      - edgecloud-network

networks:
  edgecloud-network:
    driver: bridge

volumes:
  auth_mysql_data:
  monitoring_mysql_data:
  device_mysql_data:
  alert_mysql_data: